### ISSUE TITLE
Beeper Sound function

### ISSUE THREAD

**Issue by jasonchong3329** [Ans0n-Ti0/esc-pos-encoder-ionic-demo#5]
hi 
may i know is there a "Beeper" Sound function?

i found some resource for the command for those who need can find from below link : 

https://github.com/stefanosbou/esc-pos-java/blob/master/src/main/java/io/github/escposjava/print/Commands.java
https://github.com/escpos/escpos/blob/master/lib/escpos.rb

For those who want to add into the plugin can add below code into esc-pos-encoder.js

    beeper() {
        this._queue([
            0x1b,0x42,0x05,0x01
        ]);

        return this;
    }

    cashdrawer() {
        this._queue([
            0x1b,0x70,0x00
        ]);

        return this;
    }

**Comment by ansontio** [comment]
Hello Jason,
I didn't wrap the beeper function, but you can send the raw byte code.

Maybe try the code below
`.raw([0x1b, 0x28, 0x41, 0x04, 0x00, 0x30, 0x01, 0x03, 0x0a])`
The bytes depending on the printer model.

Reference:
[Epson raw byte for beeper](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=212)

**Comment by jasonchong3329** [comment]
> Hello Jason,
> I didn't wrap the beeper function, but you can send the raw byte code.
> 
> Maybe try the code below
> `.raw([0x1b, 0x28, 0x41, 0x04, 0x00, 0x30, 0x01, 0x03, 0x0a])`
> The bytes depending on the printer model.
> 
> Reference:
> [Epson raw byte for beeper](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=212)

thank you for the reply , i got the solution already.

**Comment by ansontio** [comment]
Oh great, would you mind sharing your solution?

**Comment by jasonchong3329** [comment]
> Oh great, would you mind sharing your solution?

Yes 
I was shared in my post.

**Comment by ansontio** [comment]
Oh sorry, I didn't notice. Thank you.

**Comment by ansontio** [comment]
Updated the library. @jasonchong3329 
Added beeper and open cash drawer into esc-pos-encoder-ionic.

https://www.npmjs.com/package/esc-pos-encoder-ionic
